INSERT INTO `wtf_navgroup` (`id`,`code`,`collapse`,`icon`,`name`,`url`) VALUES ('010','010','Y','icon-dashboard','Dashboard','');
INSERT INTO `wtf_navgroup` (`id`,`code`,`collapse`,`icon`,`name`,`url`) VALUES ('011','011',NULL,'icon-dashboard','Samples','');
INSERT INTO `wtf_navgroup` (`id`,`code`,`collapse`,`icon`,`name`,`url`) VALUES ('020','020',NULL,'icon-question-sign','Devices','');
INSERT INTO `wtf_navgroup` (`id`,`code`,`collapse`,`icon`,`name`,`url`) VALUES ('030','030',NULL,'icon-briefcase','Device Templates','');
INSERT INTO `wtf_navgroup` (`id`,`code`,`collapse`,`icon`,`name`,`url`) VALUES ('040','040',NULL,'icon-briefcase','CLI Configlets','');
INSERT INTO `wtf_navgroup` (`id`,`code`,`collapse`,`icon`,`name`,`url`) VALUES ('050','050',NULL,'icon-exclamation-sign','Images and Scripts','');
INSERT INTO `wtf_navgroup` (`id`,`code`,`collapse`,`icon`,`name`,`url`) VALUES ('060','060',NULL,'icon-exclamation-sign','Reports','');
INSERT INTO `wtf_navgroup` (`id`,`code`,`collapse`,`icon`,`name`,`url`) VALUES ('070','070',NULL,'icon-legal','Network Monitoring','');
INSERT INTO `wtf_navgroup` (`id`,`code`,`collapse`,`icon`,`name`,`url`) VALUES ('080','080',NULL,'icon-legal','Configuration Files','');
INSERT INTO `wtf_navgroup` (`id`,`code`,`collapse`,`icon`,`name`,`url`) VALUES ('090','090',NULL,'icon-comment','Jobs','');
INSERT INTO `wtf_navgroup` (`id`,`code`,`collapse`,`icon`,`name`,`url`) VALUES ('100','100',NULL,'icon-briefcase','Users','');
INSERT INTO `wtf_navgroup` (`id`,`code`,`collapse`,`icon`,`name`,`url`) VALUES ('110','110',NULL,'icon-briefcase','Audit Logs','');
INSERT INTO `wtf_navgroup` (`id`,`code`,`collapse`,`icon`,`name`,`url`) VALUES ('120','120',NULL,'icon-briefcase','Administration','');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('0.010','010','#CTX#/Dashboard','Y','dashboard');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('0.020','010','My Favarite1','Y','wtf/charttest');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('0.030','010','My Favarite2','Y','wtf/buttontest');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('0.110','011','Buttons','Y','wtf/buttontest');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('0.111','011','Charts','Y','wtf/charttest');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('0.112','011','Design Test','Y','wtf/designtest');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('0.113','011','Images','Y','wtf/imagetest');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('0.114','011','Landing Page','Y','wtf/landingpage');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('0.115','011','Landing Page Tree','Y','wtf/landingpagetree');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('0.116','011','Input Components','Y','wtf/inputtest');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('0.117','011','Tab Layout','Y','wtf/tabtest');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('0.118','011','Forms','Y','wtf/formtest');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('0.119','011','Wizard Form','Y','wtf/wizardform');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('1.010','020','Device Management','Y','rest/devicemgr');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('1.020','020','Device Discovery','Y','rest/devicediscovery');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('1.030','020','Specify Probes','Y','rest/specifyprobes');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('1.040','020','Specify Credentials','Y','rest/specifycredentials');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('1.050','020','Deployed Devices','Y','rest/deploydevices');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('1.060','020','Unmanaged Devices','Y','rest/unmanageddevices');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('1.070','020','Secure Console','Y','rest/secureconsole');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('1.080','020','Device Adapter','Y','rest/deviceadapter');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('10.010','110','Audit Log','Y','rest/auditlog');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('11.010','120','Space Node Settings','Y','rest/snsettings');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('11.020','120','SNMP Manager','Y','rest/snmpmanager');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('11.030','120','Database Backup and Restore','Y','rest/dbandrestore');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('11.040','120','Licenses','Y','rest/licenses');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('11.050','120','Applications','Y','rest/applications');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('11.060','120','Space Troubleshootting','Y','rest/spacetroubleshootting');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('11.070','120','Platform Certificate','Y','rest/platform centificate');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('11.080','120','CA/CRL Certificates','Y','rest/cacrlcertificates');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('11.090','120','Authentication Servers','Y','rest/authenticationservers');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('11.110','120','SMTP Servers','Y','rest/smtpservers');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('11.120','120','Tags','Y','rest/tags');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('11.130','120','Permission Labels','Y','rest/permissionlabels');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('11.140','120','DMI Schemas','Y','rest/dmischemas');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('2.010','030','Definitions','Y','rest/definitions');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('2.020','030','Templates','Y','rest/templates');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('3.010','040','Configlets','Y','rest/configlets');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('3.020','040','Configuration View','Y','rest/configurationview');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('3.030','040','Xpath and Regex','Y','rest/xpathandregex');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('4.010','050','Images','Y','rest/images');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('4.020','050','Scripts','Y','rest/scripts');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('4.030','050','Operations','Y','rest/operations');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('4.040','050','Script Bundles','Y','rest/scriptbundles');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('5.010','060','Report Definitions','Y','rest/reportdefinitions');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('5.020','060','Generated Reports','Y','rest/generatedreports');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('6.010','070','Node List','Y','rest/nwnodelist');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('6.020','070','Search','Y','rest/nwsearch');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('6.030','070','Outages','Y','rest/nwoutages');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('6.040','070','Dashboard','Y','rest/nwdashboard');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('6.050','070','Events','Y','rest/nwevents');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('6.060','070','Alarms','Y','rest/nwalarms');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('6.070','070','Notifications','Y','rest/nwnotifications');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('6.080','070','Assets','Y','rest/nwassets');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('6.090','070','Reports','Y','rest/nwresports');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('6.110','070','Charts','Y','rest/nwcharts');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('6.120','070','Topology','Y','rest/nwtopology');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('6.130','070','Admin','Y','rest/nwadmin');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('7.010','080','Config Files Management','Y','rest/cfmanagement');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('8.010','090','Job Management','Y','rest/jobmanagement');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('9.010','100','Roles','Y','rest/roles');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('9.020','100','User Accounts','Y','rest/useraccounts');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('9.030','100','Remote Profiles','Y','rest/remoteprofiles');
INSERT INTO `wtf_navitem` (`id`,`groupId`,`name`,`target`,`url`) VALUES ('9.040','100','User Sessions','Y','rest/usersessions');
